# See subjects.http for getting all cards of a subject

# Get single card ✅
GET /api/cards/4
Host: 127.0.0.1:8000

###
# Create card ✅
POST /api/cards
Host: 127.0.0.1:8000
Content-Type: application/json

{
  "backsideContent": "Hallo Welt",
  "frontsideContent": "Hello World",
  "subjectId": 1
}

###
# Update card ✅
PATCH /api/cards/21
Host: 127.0.0.1:8000
Content-Type: application/json

{
  "backsideContent": "Hallo Welt!",
  "frontsideContent": "Hello World!"
}

###
# Delete card ✅
DELETE /api/cards/21
Host: 127.0.0.1:8000

###
