# See subjects.http for getting a collection of cycles for a subject

###
# Succeed cycle ✅
PATCH /api/cycle/49/succeed
Host: 127.0.0.1:8000

###
# Fail cycle ✅
PATCH /api/cycle/1/fail
Host: 127.0.0.1:8000
