index:
    path: /
    controller: App\Controller\DefaultController::indexAction

cycle:
    path: /cycle/{subjectId}
    controller: App\Controller\CycleController::cycleAction

cycleFail:
    path: /cycleFail/{subjectId}
    controller: App\Controller\CycleController::cycleFailAction

cycleSucceed:
    path: /cycleSucceed/{subjectId}
    controller: App\Controller\CycleController::cycleSucceedAction

cycleSummary:
    path: /cycleSummary/{subjectId}
    controller: App\Controller\CycleController::cycleSummaryAction

loadCycle:
    path: /loadCycle/{subjectId}
    controller: App\Controller\CycleController::loadCycleAction

cards:
    path: /cards/{subjectId}
    controller: App\Controller\DefaultController::cardsAction

addSubject:
    path: /addSubject
    controller: App\Controller\SubjectController::addAction

addCard:
    path: /addCard/{subjectId}
    controller: App\Controller\CardController::addAction
