subjects:
    path: /api/subjects/{id}
    controller: App\Controller\SubjectController::apiEndpointAction

index:
    path: /
    controller: App\Controller\DefaultController::indexAction

cycle:
    path: /{slug}
    controller: App\Controller\CycleController::cycleAction

cycleFail:
    path: /{slug}/cycleFail
    controller: App\Controller\CycleController::cycleFailAction

cycleSucceed:
    path: /{slug}/cycleSucceed
    controller: App\Controller\CycleController::cycleSucceedAction

cycleSummary:
    path: /{slug}/cycleSummary
    controller: App\Controller\CycleController::cycleSummaryAction

cards:
    path: /{slug}/cards
    controller: App\Controller\DefaultController::cardsAction

addCard:
    path: /{slug}/addCard
    controller: App\Controller\CardController::addAction

addSubject:
    path: /addSubject
    controller: App\Controller\SubjectController::addAction
