index:
    path: /
    controller: App\Controller\DefaultController::indexAction

firstRun:
    path: /firstRun
    controller: App\Controller\DefaultController::firstRunAction

cycle:
    path: /cycle/{subjectId}
    controller: App\Controller\CycleController::cycleAction

cycleFail:
    path: /cycleFail/{subjectId}
    controller: App\Controller\CycleController::cycleFailAction

cycleSucceed:
    path: /cycleSucceed/{subjectId}
    controller: App\Controller\CycleController::cycleSucceedAction

cards:
    path: /cards/{subjectId}
    controller: App\Controller\DefaultController::cardsAction

addSubject:
    path: /addSubject
    controller: App\Controller\SubjectController::addAction
